### ISSUE TITLE
Keine Indexierung, wenn Enrichment-Werte zu groß sind (opus_import_data)

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/opus4-search#107]
Beim Versuch Dokumente zu indexieren, tritt in seltenen Fällen folgende Meldung auf:
failed updating slice of documents: 400 OK

Die Meldung stammt aus der Methode addDocumentsToIndex in der Klasse Adapter.php
https://github.com/OPUS4/opus4-search/blob/5f926d828f8b4225d797881ad65c241af8d37bad/src/Solr/Solarium/Adapter.php

Im solr.log (search) findet sich folgendes:
o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Exception writing document id 4014 to the index; possible analysis error: Document contains at least one immense term in field="enrichment_opus_import_data" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[123, 34, 115, 116, 97, 116, 117, 115, 34, 58, 34, 111, 107, 34, 44, 34, 109, 101, 115, 115, 97, 103, 101, 45, 116, 121, 112, 101, 34, 58]...', original message: bytes can be at most 32766 in length; got 49759. Perhaps the document has an indexed string field (solr.StrField) which is too large

**Comment by vgerlach** [comment]
Von der Lucene-Seite (https://www.searchstax.com/docs/hc/contains-at-least-one-immense-term/) werden folgende Lösungsmöglichkeiten vorgeschlagen:
To remedy this situation, consider these strategies:
-     Change the field definition in the schema so the field is not indexed.
-     Change the field type to “text” or some other tokenized field.
-     Modify your solr.config file to truncate incoming strings so they don’t overflow their fields.

**Comment by vgerlach** [comment]
betroffenes System: OPUS-Version 4.8.0.2 mit PHP 7

**Comment by j3nsch** [comment]
Der Feldtyp für Enrichments im Index ist **string**. Strings haben eine begrenzte Größe und werden für die Suche nicht zerlegt. Sie sind gut für Facetten geeignet. Mit dem Typ **text** könnten die Inhalte größer sein, aber dann findet eine Zerlegung des Inhalts für die Suche statt. Das macht sicherlich nicht für alle Enrichments Sinn. Evtl. könnte man das für einzelne Enrichments konfigurierbar machen. 

Momentan wird es hier aber keine Änderungen geben, da das Enrichment-System, sich stark verändern wird und weitere Anpassungen erst nach dem Umstieg auf Doctrine Sinn machen.

Man könnte jetzt überlegen, ob einzelne Enrichments von der Indexierung ausgeschlossen werden sollten. Im Fall von `opus_import_data` scheint es nicht sinnvoll die Rohdaten vom Import mit in den Index aufzunehmen. Wie so eine Filterung umgesetzt werden kann, ist noch unklar, da das Indexing-XML mit XSLT aus dem vollständigen OPUS-XML erzeugt wird. Am einfachsten wäre es vermutlich Enrichments direkt aus dem OPUS-XML auszuschließen, sozusagen als INTERNE Enrichments. Gerade bei der Unterscheidung zwischen internen und externen Informationen sollen die kommenden Änderungen am Enrichment-System viele Verbesserungen bringen. 

Die schnelle Lösung für die betroffene Instanz wäre das Löschen der zu langen Enrichments. Das sollte bei dem betroffenen Feld kein Problem darstellen. Man sollte klären, ob es überhaupt aktiv durch die Administratoren verwendet wird.

**Comment by j3nsch** [comment]
Wir können auch schauen, ob wir für 4.8.1 die Felder erst einmal einfach abschneiden, damit sie nicht zu Fehlern führen, bevor wir sie dann später komplett aus der Indexierung entfernen.

**Comment by vgerlach** [comment]
Das fände ich gut. Am besten natürlich mit Hinweis für den Nutzer, dass der Feldinhalt abgeschnitten wird.

**Comment by j3nsch** [comment]
Das Problem tritt vermutlich erst auf seitdem wir größere Enrichments erlaubt haben. Das heißt aber auch, dass vorher und wahrscheinlich auch jetzt, das Enrichment **opus-import-data** bei sehr großen Rohdaten abgeschnitten wird. Das ist ein separates Problem, über das nachgedacht werden muss. Die Rohdaten werden technisch nicht verwendet. Sie dienen einer manuellen Prüfung des Imports, die wahrscheinlich kaum jemand macht. Es sei denn es gibt Probleme.

**Comment by extracts** [comment]
Der Ansatz "[truncate incoming strings so they don’t overflow their fields](http://www.sitecorevarun.com/2015/08/resolved-solr-exceptions-document.html)" wäre einen Versuch wert. Sollte dafür noch ein Test geschrieben werden, der eines der Enrichment Felder mit >32kb Text befüllt?

**Comment by alw-bsz** [comment]
Das Feld opus_import_data müsste mit den DOI-Import neu hinzugekommen sein und wird nach unserem Kenntnisstand nur für diesen verwendet. In dem Feld wird der originale Datensatz von Crossref gehalten. Eine Indexierung ist nicht sinnvoll. Das Feld sollte aus der Indexierung genommen werden.

**Comment by j3nsch** [comment]
Die Truncate-Lösung ist das, was vielleicht jetzt gemacht werden kann und in jedem Fall sinnvoll ist, weil es immer Inhalte geben kann, die zu lang sind. Das Ausschließen des Feldes von der Indexierung ist schwieriger. Der Code ist dafür nicht designed. Mit dem überarbeiteten Enrichment-System, OPUS 4.9+, wäre es einfacher, weil das System durchdachter ist und klarere Unterscheidungen zwischen (Enrichment)-Feldern ermöglicht.

Ich habe keine Möglichkeit gefunden, um Solr zu sagen es soll bestimmte Enrichment-Elemente ignorieren. Die nächste Möglichkeit wäre zu versuchen diese Enrichments im XSLT für die Suche zu filtern, also nicht mit in das Solr-XML aufzunehmen.
    
    src/Solr/Document/solr.xslt
    
In dem XSTL könnten man eine PHP Funktion verwenden, der man den Namen des Enrichments übergibt und die entscheidet, ob das Enrichment mit aufgenommen werden soll. Der erste Schritt wäre einfach nur die Umsetzung der Funktion. Die Konfiguration sollte erst einmal über eine Blacklist erfolgen. Später macht vermutlich ein Whitelisting mehr Sinn. Im OAI-Modul werden PHP Funktionen im XSTL verwendet. Das kann Hinweise für die Umsetzung geben. Diese Funktionalität hier sollte nicht als Zend-ViewHelper umgesetzt werden, um diese Abhängigkeit nicht in **opus4-search** einzuführen.

**Comment by j3nsch** [comment]
Das SOLR-Xslt verwendet bereits eine PHP Funktion. Nach dem gleichen Muster kann die neue Funktion umgesetzt werden.
