### ISSUE TITLE
Solr 9.x Admin UI ist mit Vagrant vom Host OS nicht aufrufbar

### ISSUE THREAD

**Issue by extracts** [OPUS4/opus4-search#109]
Mit Vagrant lässt sich unter Solr 9.x die Solr-Admin-Oberfläche vom Host OS über http://localhost:9983 nicht aufrufen. Man erhält als Fehlermeldung `ERR_CONNECTION_RESET`.

Im Vagrantfile ist, so wie bereits zuvor für Solr 7.x, das "port forwarding" für Solr wie folgt definiert:

    config.vm.network "forwarded_port", guest: 8983, host: 9983, host_ip: "127.0.0.1"

**Comment by j3nsch** [comment]
Mit dem Vagrantfile für OPUS 4.7.1.2 funktioniert das noch. Dort werden Ubuntu 20 und Solr 7.7.2 verwendet.

**Comment by j3nsch** [comment]
In dem Vagrantfile für OPUS 4.8.1 (aktuell MASTER Branch) mit Ubuntu 22 und Solr 7.7.2 funktioniert es auch noch. Es scheint also an Solr 9 zu liegen.

**Comment by j3nsch** [comment]
Ich vermute es hat mit der Konfiguration von Solr zu tun und der IP Adresse des Clients, also der Forwarding Konfiguration im Vagrantfile. Der Zugriff auf die Admin-UI von Solr ist stärker eingeschränkt worden. Man müsste das in der Solr Dokumentation prüfen und schauen, ob sich da von außen (Vagrantfile) durch ein anderes Setup des Forwarding oder von Innen durch Änderungen in der Solr Konfiguration fixen lässt.

**Comment by extracts** [comment]
From the [Solr documentation](https://solr.apache.org/guide/solr/latest/deployment-guide/taking-solr-to-production.html#security-considerations):

> It is also strongly recommended that Solr listen to only those network interfaces that are strictly required. To prevent administrators from unintentionally exposing Solr more broadly, Solr only listens on the loopback interface ("127.0.0.1") by default. Most deployments will need to change this value to something less restrictive so that it can be reached from other boxes. This can be done by setting a SOLR_JETTY_HOST value in your environment’s "include script" (solr.in.sh or solr.in.cmd):
```
 ----
 SOLR_JETTY_HOST="0.0.0.0"
 ----
 ```
> The same setting is also available as the -Dsolr.jetty.host System Property.

**Comment by j3nsch** [comment]
Danke! Mach mal für die Application auch noch. :-)
