### ISSUE TITLE
Sortierung der Facetten lässt sich nicht mehr einzeln einstellen

### ISSUE THREAD

**Issue by bfalkenstein** [OPUS4/opus4-search#132]
Die Facetten sind per Default nach der Anzahl sortiert. Eine alphabetische Sortierung konnte bisher in der config.ini z.B. mit 
`search.facet.year.sort = lexi`
für jede Facette einzeln eingestellt werden. 
Das funktioniert seit v 4.8 nicht mehr richtig. Fügt man die o.g. Zeile ein, werden **alle** Facetten alphabetisch sortiert, statt nur "year". 
(Getestet mit v 4.8.0.5, Solr 9, PHP 8.1)

**Comment by j3nsch** [comment]
Das Problem hat sich mit den Änderungen für den Umstieg auf eine neuere Solarium-Version für PHP 8 eingeschlichen und tritt daher nicht mit PHP 7 auf.

Es gibt jetzt eine neue Version, **4.8.0.1**, von **opus4-search**, die das Problem behebt. Der neue Release kann mit `composer update` installiert werden.

**Comment by bfalkenstein** [comment]
Danke fürs schnelle Fixen!
